### ISSUE TITLE
RFC PiCloud 

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/workflow#15]
PiCloud was bought by Dropbox in late 2013. Multyvac seems to be offering similar service now.

What shall we do with PiCloud in Workflow?  

- if not needed, shall we deprecate it and remove from the code base?
- if still needed, shall we separate it to `contrib` or some such?

**Comment by kaplun** [comment]
I can't find traces of PiCloud in the code so I assume it has been already resolved.
