### ISSUE TITLE
RFC Celery 

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/workflow#16]
It would be nice to port functionality from *Invenio* where workflows are executed on Celery (http://www.celeryproject.org/) similarly to `PhoenixWorkflowEngine` (https://github.com/inveniosoftware/workflow/blob/master/workflow/engine.py#L536-L571) that is already included in `workflow.engine`.

- [ ] run workflows as `celery` tasks
- [ ] use persistent storage for workflow engine status and data

--
ping @jalavik

**Comment by kaplun** [comment]
@jalavik is this still meaningful? Was it moved to invenio-workflows?

**Comment by kaplun** [comment]
This is now https://github.com/inveniosoftware-contrib/invenio-workflows
