### ISSUE TITLE
RFC Unused functionality: PheonixWorkflowEngine, Seman/Lucene

### ISSUE THREAD

**Issue by dset0x** [inveniosoftware/workflow#30]
Based on proposals and observations that were brought up during the [Invenio Developer Forum on 2015-03-23](https://indico.cern.ch/event/376433/).

There is some functionality and references in the current Workflow code that we do not use, or consider generic enough to be left in the main package. Namely:

* Special handling for objects with the [`TokenizedDocument`](https://github.com/inveniosoftware/workflow/blob/74d994bba6eeceff7f1f0d1cce49bbf6b965e23a/workflow/engine.py#L263) attribute.
These objects are likely created for Apache Lucene, based on the only reference I could find, which lies [here](https://svnweb.cern.ch/trac/rcarepo/wiki/InspireWorkflowEngineSpecs). This should also allow us to clean code found elsewhere, such as the [`CALLFUNC` pattern](https://github.com/inveniosoftware/workflow/blob/74d994bba6eeceff7f1f0d1cce49bbf6b965e23a/workflow/patterns/utils.py#L445).

* The functionality that `PhoenixWorkflowEngine` provided will be available by the `GenericWorkflowEngine` interface when [this branch](https://github.com/dset0x/workflow/tree/delegate-storage) is completed and merged. Therefore it should be safe to remove (note that in the branch it has already been removed).

cc @jalavik @jirikuncar @tiborsimko @PXke @romanchyla

**Comment by tiborsimko** [comment]
See also previous discussion in #15

**Comment by dset0x** [comment]
To this RFC I would like to add `config.py`, which we find to also be unused. The need for global configuration should be covered by `store` (to be renamed to `extra_data`).

**Comment by romanchyla** [comment]
i have to admit i'm not familiar with the `store`  :)

will the workflow, as a library, be still usable standalone after that change? or is the `store` another library (a dependency)?

**Comment by dset0x** [comment]
@romanchyla By `store` I was referring to `GenericWorkflowEngine.store`. Yes, the goal is to keep the library independent.

**Comment by kaplun** [comment]
I think that had been implemented in 8d1968c94845ad1ae6bcd79dea49f945322c1914. and in aea35ffc1afc30c9afe920cbf34f7110dcf30f65
